Repository ArkEcosystem/typescript-peers, pull requests merged in 2019-08, with the labels that each got.

#8 fix: hardcoded ports & add tests
  __tests__/discovery.test.ts
  __tests__/mocks/peers.ts
  package.json
  src/discovery.ts
  src/index.ts
  src/types.ts
  yarn.lock
Labels: Complexity: High, Type: Bugfix

#9 chore: bump version & update changelog
  CHANGELOG.md
  package.json
Labels: Complexity: Low, Type: Task

#10 ci: run tests on CircleCI
  .circleci/config.yml
Labels: Complexity: Low

#12 fix: don't use p2p port from github peers
  __tests__/discovery.test.ts
  src/discovery.ts
Labels: Complexity: Low, Type: Bugfix

#13 release: 0.2.1
  CHANGELOG.md
  package.json
Labels: Complexity: Low, Type: Release
