Repository ArkEcosystem/typescript-peers, pull requests merged in 2019-07, with the labels that each got.

#1 docs: remove global add
  README.md
Labels: Complexity: Low, Type: Documentation

#2 feat: return additional peer data
  src/discovery.ts
Labels: Complexity: Low, Type: Feature

#3 fix: force v2 peer endpoint
  src/discovery.ts
Labels: Complexity: Low, Type: Bugfix

#5 chore: setup probot/stale configuration
  .github/stale.yml
Labels: Complexity: Low, Type: Task

#6 chore(readme): add lead maintainer information
  README.md
Labels: Complexity: Low, Type: Task
